import json

# Opening JSON file with description of all tests and return dictionary for input to latex document
json_test_file = open('tests.json')
List_of_tests = json.load(json_test_file)


def create_testgroup(fp, test_group):
    # Gets a single testgroup from the dictionary created from the JSON testfile
    # then creates latex and inserts into the main file that contains the extra information
    # F-String has to be escaped hence code looks a bit ugly


    tgroup_id = f"{test_group['Group number']}: {test_group['Group name']}"
    
    rationale = test_group['Rationale for test']
    test_setup = test_group['Test setup']
    areas = test_group['Possible test areas']
    tcontact = test_group['Technical contact']
    
    fp.write(f'\\section{{{tgroup_id}}}\n\n')
    fp.write(f'\\subsection*{{Rationale}}\n\n')
    fp.write(f'{rationale}\n\n')
    fp.write(f'\\subsection*{{Test setup}}\n\n')
    fp.write(f'{test_setup}\n\n')
    fp.write(f'\\subsubsection*{{Areas}}\n\n')
    fp.write(f'{areas}\n\n')
    fp.write(f'\\subsubsection*{{Technical contact}}\n\n')
    fp.write(f'{tcontact}\n\n')
    fp.write(f'\\section*{{Test within this testgroup}}\n\n')

    # This section generates information on each test
    for test in test_group['Tests']:
        tid = f"{test['Test id']}  {test['Test name']}"
        t_text = test["Test text"]
        t_power = test["Power or power range"]
        t_time = test["Test time"]
        t_location = test["Location of transmitter"]
        t_comment =  test["Test comment"]

        fp.write(f'\\subsection{{{tid}}}\n\n')
        fp.write('\\noindent\\rule[0.5ex]{\linewidth}{1pt} \n')
        
        
        fp.write(f'{t_text}\n')
        fp.write(f'\\subsubsection*{{Power or power range}}\n')
        fp.write(f'{t_power}\n')
        fp.write(f'\\subsubsection*{{Test running time}}\n')
        fp.write(f'{t_time}\n')
        fp.write(f'\\subsubsection*{{Location of transmitter}}\n')
        fp.write(f'{t_location}\n')
        fp.write(f'\\subsubsection*{{Comment}}\n')
        fp.write(f'{t_comment}\n')

       
        




# create a text file for writing
with open('tests.tex', 'w') as fp:
    fp.write('% Content below is autogenerated \n')
    create_testgroup(fp, List_of_tests["Test groups"][0])
